config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#home', as: :home
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/concerns/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail, :ingredient, presence: true
  validates_uniqueness_of :cocktail, scope: [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def home
  end

  def index
    @cocktails = Cocktail.all
    # @cocktail = Cocktail.find(params[:id])
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :title, :body, photos: [])
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  private

  def dose_params
    params.require(:dose).permit(:cocktail_id, :ingredient_id, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/_form.html.erb
<!-- app/views/articles/_form.html.erb -->
<%= simple_form_for(article) do |f| %>
  <!-- [...] -->
  <%= f.input :photo, as: :file input_html: { multiple: true } %>
  <!-- [...] -->
<% end %>

app/views/cocktails/home.html.erb
<%= link_to new_cocktail_path do %>
  <div class="background">
    <p class="btn btn-flat btn-home" href="#">Create your <span class="favorite">favorite</span> cocktail</p>
  </div>
<% end %>

<h1>Cocktails</h1>

app/views/cocktails/index.html.erb
<%= link_to new_cocktail_path do %>
  <div id="add_cocktail">
    <button class="btn btn-flat btn-index">Create your <span class="favorite">favorite</span> cocktail</button>
  </div>
<% end %>


<div class="container mt-3">
  <div class="cards">
    <% @cocktails.each do |cocktail| %>
      <%= link_to cocktail_path(cocktail) do %>
        <%= cl_image_tag("https://res.cloudinary.com/rosemaryakl/image/upload/v1595675817/san_fransisco.jpg", width: 400, height: 300, crop: :fill) %>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container margin-top">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1> Cocktail Name :</h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.button :submit, class: 'btn btn-primary btn-index' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">

  <h1 class="margin-top"><%= @cocktail.name %></h1>
  <%= link_to "Back", cocktails_path %>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3 class="margin-top">Recipe :</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <h3>Other Ingredients ?</h3>
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.association :ingredient %>
          <%= f.input :description %>
          <%= f.button :submit, class: "btn btn-primary btn-index" %>
          <%= f.button :button, "Reset", type: "reset", class: "btn-outline-secondary" %>
          <%= link_to 'Cancel', cocktails_path, class: 'btn btn-danger'  %>
        <% end %>
    </div>
  </div>

app/views/doses/new.html.erb
<div class="container margin-top">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Design your cocktail :</h1>
        <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.association :ingredient %>
          <%= f.input :description %>
          <%= f.button :submit, class: "btn btn-primary btn-index" %>
          <%= link_to "Back", cocktails_path, class: "btn btn-primary btn-index"%>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  </head>

  <body>

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to "#", class: "navbar-brand" do %>
        <p class="signature">My Little Cocktails</p>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", home_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cocktails", cocktails_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>


  </body>
</html>